[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
actix-cors = "0.7.1"
tokio = { version = "1.45.1", features = ["full"] }
core = { path = "../core" }
dotenvy = "0.15.7"
shared = { path = "../../shared", features = ["actix"] }
